#!/usr/bin/env python3
"""Add exact host-backed object constants required by the 40-app corpus."""
from pathlib import Path

root = Path("build/LiveExec32/GuestFrameworks")
constants = {
    'AddressBook': [
        ('kABGroupNameProperty', 'string'),
        ('kABPersonCreationDateProperty', 'string'),
        ('kABPersonDateProperty', 'string'),
        ('kABPersonModificationDateProperty', 'string'),
    ],
    'AVFoundation': [
        ('AVAssetExportPreset1280x720', 'string'),
        ('AVAssetExportPreset1920x1080', 'string'),
        ('AVAssetExportPreset640x480', 'string'),
        ('AVAssetExportPreset960x540', 'string'),
        ('AVAssetExportPresetAppleM4A', 'string'),
        ('AVAssetExportPresetPassthrough', 'string'),
        ('AVChannelLayoutKey', 'string'),
        ('AVEncoderBitRateKey', 'string'),
        ('AVLinearPCMIsNonInterleaved', 'string'),
        ('AVPlayerItemFailedToPlayToEndTimeNotification', 'string'),
        ('AVPlayerItemNewAccessLogEntryNotification', 'string'),
        ('AVPlayerItemNewErrorLogEntryNotification', 'string'),
        ('AVPlayerItemPlaybackStalledNotification', 'string'),
        ('AVURLAssetPreferPreciseDurationAndTimingKey', 'string'),
        ('AVURLAssetReferenceRestrictionsKey', 'string'),
        ('AVVideoAverageBitRateKey', 'string'),
        ('AVVideoCodecH264', 'string'),
        ('AVVideoCodecKey', 'string'),
        ('AVVideoCompressionPropertiesKey', 'string'),
        ('AVVideoHeightKey', 'string'),
        ('AVVideoMaxKeyFrameIntervalKey', 'string'),
        ('AVVideoProfileLevelH264High40', 'string'),
        ('AVVideoProfileLevelKey', 'string'),
        ('AVVideoWidthKey', 'string'),
        ('AVAssetExportPresetHighestQuality', 'string'),
        ('AVCaptureDeviceWasConnectedNotification', 'string'),
        ('AVCaptureDeviceWasDisconnectedNotification', 'string'),
        ('AVAudioSessionMediaServicesWereResetNotification', 'string'),
        ('AVAudioSessionModeDefault', 'string'),
        ('AVAudioSessionPortAirPlay', 'string'),
        ('AVAudioSessionPortBluetoothA2DP', 'string'),
        ('AVAudioSessionPortBuiltInReceiver', 'string'),
        ('AVAudioSessionPortBuiltInSpeaker', 'string'),
        ('AVAudioSessionPortHDMI', 'string'),
        ('AVAudioSessionPortHeadphones', 'string'),
        ('AVAudioSessionPortLineOut', 'string'),
        ('AVCaptureSessionPreset640x480', 'string'),
        ('AVCaptureSessionPresetHigh', 'string'),
        ('AVCaptureSessionPresetLow', 'string'),
        ('AVCaptureSessionPresetMedium', 'string'),
        ('AVCaptureSessionPresetPhoto', 'string'),
        ('AVFileTypeAppleM4A', 'string'),
        ('AVFileTypeQuickTimeMovie', 'string'),
        ('AVFoundationErrorDomain', 'string'),
        ('AVLayerVideoGravityResizeAspectFill', 'string'),
        ('AVMediaTypeAudio', 'string'),
        ('AVMediaTypeVideo', 'string'),
        ('AVMetadataCommonKeyAlbumName', 'string'),
        ('AVMetadataCommonKeyArtist', 'string'),
        ('AVMetadataCommonKeyArtwork', 'string'),
        ('AVMetadataCommonKeyTitle', 'string'),
        ('AVMetadataKeySpaceCommon', 'string'),
        ('AVMetadataKeySpaceiTunes', 'string'),
        ('AVMetadataObjectTypeAztecCode', 'string'),
        ('AVMetadataObjectTypeCode128Code', 'string'),
        ('AVMetadataObjectTypeCode39Code', 'string'),
        ('AVMetadataObjectTypeCode39Mod43Code', 'string'),
        ('AVMetadataObjectTypeCode93Code', 'string'),
        ('AVMetadataObjectTypeDataMatrixCode', 'string'),
        ('AVMetadataObjectTypeEAN13Code', 'string'),
        ('AVMetadataObjectTypeEAN8Code', 'string'),
        ('AVMetadataObjectTypeITF14Code', 'string'),
        ('AVMetadataObjectTypeInterleaved2of5Code', 'string'),
        ('AVMetadataObjectTypePDF417Code', 'string'),
        ('AVMetadataObjectTypeQRCode', 'string'),
        ('AVMetadataObjectTypeUPCECode', 'string'),
        ('AVPlayerItemTimeJumpedNotification', 'string'),
    ],
    'Accounts': [
        ('ACAccountStoreDidChangeNotification', 'string'),
        ('ACAccountTypeIdentifierFacebook', 'string'),
        ('ACAccountTypeIdentifierTwitter', 'string'),
        ('ACFacebookAppIdKey', 'string'),
        ('ACFacebookAudienceEveryone', 'string'),
        ('ACFacebookAudienceFriends', 'string'),
        ('ACFacebookAudienceKey', 'string'),
        ('ACFacebookAudienceOnlyMe', 'string'),
        ('ACFacebookPermissionsKey', 'string'),
    ],
    'AddressBookUI': [
        ('ABPersonEmailAddressesProperty', 'string'),
        ('ABPersonPhoneNumbersProperty', 'string'),
        ('ABPersonUrlAddressesProperty', 'string'),
    ],
    'AssetsLibrary': [
        ('ALAssetPropertyAssetURL', 'string'),
        ('ALAssetPropertyDate', 'string'),
        ('ALAssetPropertyDuration', 'string'),
        ('ALAssetPropertyLocation', 'string'),
        ('ALAssetPropertyOrientation', 'string'),
        ('ALAssetPropertyRepresentations', 'string'),
        ('ALAssetPropertyType', 'string'),
        ('ALAssetPropertyURLs', 'string'),
        ('ALAssetTypePhoto', 'string'),
        ('ALAssetTypeVideo', 'string'),
        ('ALAssetsGroupPropertyName', 'string'),
        ('ALAssetsGroupPropertyType', 'string'),
        ('ALAssetsGroupPropertyURL', 'string'),
        ('ALAssetsLibraryChangedNotification', 'string'),
    ],
    'CFNetwork': [
        ('kCFGetAddrInfoFailureKey', 'string'),
        ('kCFHTTPAuthenticationSchemeBasic', 'string'),
        ('kCFStreamPropertyHTTPFinalURL', 'string'),
        ('kCFStreamPropertyHTTPRequestBytesWrittenCount', 'string'),
        ('kCFStreamPropertySSLPeerTrust', 'string'),
        ('kCFHTTPAuthenticationSchemeDigest', 'string'),
        ('kCFStreamPropertyHTTPProxyHost', 'string'),
        ('kCFStreamPropertyHTTPProxyPort', 'string'),
        ('kCFStreamPropertyHTTPSProxyHost', 'string'),
        ('kCFStreamPropertyHTTPSProxyPort', 'string'),
    ],
    'CoreBluetooth': [
        ('CBAdvertisementDataManufacturerDataKey', 'string'),
        ('CBAdvertisementDataServiceUUIDsKey', 'string'),
        ('CBCentralManagerOptionShowPowerAlertKey', 'string'),
        ('CBCentralManagerScanOptionAllowDuplicatesKey', 'string'),
    ],
    'CoreData': [
        ('NSErrorMergePolicy', 'merge:NSErrorMergePolicyType'),
        ('NSInMemoryStoreType', 'string'),
        ('NSInsertedObjectsKey', 'string'),
        ('NSManagedObjectContextDidSaveNotification', 'string'),
        ('NSManagedObjectContextObjectsDidChangeNotification', 'string'),
        ('NSMergeByPropertyObjectTrumpMergePolicy', 'merge:NSMergeByPropertyObjectTrumpMergePolicyType'),
        ('NSMergeByPropertyStoreTrumpMergePolicy', 'merge:NSMergeByPropertyStoreTrumpMergePolicyType'),
        ('NSOverwriteMergePolicy', 'merge:NSOverwriteMergePolicyType'),
        ('NSRefreshedObjectsKey', 'string'),
        ('NSRollbackMergePolicy', 'merge:NSRollbackMergePolicyType'),
        ('NSSQLiteErrorDomain', 'string'),
        ('NSSQLiteManualVacuumOption', 'string'),
        ('NSSQLitePragmasOption', 'string'),
        ('NSUpdatedObjectsKey', 'string'),
        ('NSDeletedObjectsKey', 'string'),
        ('NSManagedObjectContextWillSaveNotification', 'string'),
    ],
    'CoreFoundation': [
        ('kCFStreamPropertySOCKSPassword', 'string'),
        ('kCFStreamPropertySOCKSProxy', 'string'),
        ('kCFStreamPropertySOCKSProxyHost', 'string'),
        ('kCFStreamPropertySOCKSProxyPort', 'string'),
        ('kCFStreamPropertySOCKSUser', 'string'),
        ('kCFStreamPropertySocketSecurityLevel', 'string'),
        ('kCFStringTransformToLatin', 'string'),
        ('NSCalendarIdentifierBuddhist', 'string'),
        ('NSCalendarIdentifierChinese', 'string'),
        ('NSCalendarIdentifierCoptic', 'string'),
        ('NSCalendarIdentifierEthiopicAmeteAlem', 'string'),
        ('NSCalendarIdentifierEthiopicAmeteMihret', 'string'),
        ('NSCalendarIdentifierGregorian', 'string'),
        ('NSCalendarIdentifierHebrew', 'string'),
        ('NSCalendarIdentifierISO8601', 'string'),
        ('NSCalendarIdentifierIndian', 'string'),
        ('NSCalendarIdentifierIslamic', 'string'),
        ('NSCalendarIdentifierIslamicCivil', 'string'),
        ('NSCalendarIdentifierJapanese', 'string'),
        ('NSCalendarIdentifierPersian', 'string'),
        ('NSCalendarIdentifierRepublicOfChina', 'string'),
        ('NSStreamFileCurrentOffsetKey', 'string'),
        ('NSStreamSocketSecurityLevelKey', 'string'),
        ('NSStreamSocketSecurityLevelNegotiatedSSL', 'string'),
        ('NSURLAttributeModificationDateKey', 'string'),
        ('NSURLContentAccessDateKey', 'string'),
        ('NSURLContentModificationDateKey', 'string'),
        ('NSURLCreationDateKey', 'string'),
        ('NSURLFileAllocatedSizeKey', 'string'),
        ('NSURLFileResourceIdentifierKey', 'string'),
        ('NSURLFileResourceTypeKey', 'string'),
        ('NSURLFileSecurityKey', 'string'),
        ('NSURLFileSizeKey', 'string'),
        ('NSURLHasHiddenExtensionKey', 'string'),
        ('NSURLIsAliasFileKey', 'string'),
        ('NSURLIsDirectoryKey', 'string'),
        ('NSURLIsExecutableKey', 'string'),
        ('NSURLIsHiddenKey', 'string'),
        ('NSURLIsMountTriggerKey', 'string'),
        ('NSURLIsPackageKey', 'string'),
        ('NSURLIsReadableKey', 'string'),
        ('NSURLIsRegularFileKey', 'string'),
        ('NSURLIsSymbolicLinkKey', 'string'),
        ('NSURLIsSystemImmutableKey', 'string'),
        ('NSURLIsUbiquitousItemKey', 'string'),
        ('NSURLIsUserImmutableKey', 'string'),
        ('NSURLIsVolumeKey', 'string'),
        ('NSURLIsWritableKey', 'string'),
        ('NSURLLabelNumberKey', 'string'),
        ('NSURLLinkCountKey', 'string'),
        ('NSURLLocalizedLabelKey', 'string'),
        ('NSURLLocalizedNameKey', 'string'),
        ('NSURLLocalizedTypeDescriptionKey', 'string'),
        ('NSURLNameKey', 'string'),
        ('NSURLParentDirectoryURLKey', 'string'),
        ('NSURLPathKey', 'string'),
        ('NSURLPreferredIOBlockSizeKey', 'string'),
        ('NSURLTotalFileAllocatedSizeKey', 'string'),
        ('NSURLTotalFileSizeKey', 'string'),
        ('NSURLTypeIdentifierKey', 'string'),
        ('NSURLUbiquitousItemDownloadingErrorKey', 'string'),
        ('NSURLUbiquitousItemDownloadingStatusCurrent', 'string'),
        ('NSURLUbiquitousItemDownloadingStatusDownloaded', 'string'),
        ('NSURLUbiquitousItemDownloadingStatusNotDownloaded', 'string'),
        ('NSURLUbiquitousItemHasUnresolvedConflictsKey', 'string'),
        ('NSURLUbiquitousItemIsDownloadingKey', 'string'),
        ('NSURLUbiquitousItemIsUploadedKey', 'string'),
        ('NSURLUbiquitousItemIsUploadingKey', 'string'),
        ('NSURLUbiquitousItemUploadingErrorKey', 'string'),
        ('NSURLVolumeAvailableCapacityKey', 'string'),
        ('NSURLVolumeCreationDateKey', 'string'),
        ('NSURLVolumeIdentifierKey', 'string'),
        ('NSURLVolumeIsAutomountedKey', 'string'),
        ('NSURLVolumeIsBrowsableKey', 'string'),
        ('NSURLVolumeIsEjectableKey', 'string'),
        ('NSURLVolumeIsInternalKey', 'string'),
        ('NSURLVolumeIsJournalingKey', 'string'),
        ('NSURLVolumeIsLocalKey', 'string'),
        ('NSURLVolumeIsReadOnlyKey', 'string'),
        ('NSURLVolumeIsRemovableKey', 'string'),
        ('NSURLVolumeLocalizedFormatDescriptionKey', 'string'),
        ('NSURLVolumeLocalizedNameKey', 'string'),
        ('NSURLVolumeMaximumFileSizeKey', 'string'),
        ('NSURLVolumeNameKey', 'string'),
        ('NSURLVolumeResourceCountKey', 'string'),
        ('NSURLVolumeSupportsAdvisoryFileLockingKey', 'string'),
        ('NSURLVolumeSupportsCasePreservedNamesKey', 'string'),
        ('NSURLVolumeSupportsCaseSensitiveNamesKey', 'string'),
        ('NSURLVolumeSupportsExtendedSecurityKey', 'string'),
        ('NSURLVolumeSupportsHardLinksKey', 'string'),
        ('NSURLVolumeSupportsJournalingKey', 'string'),
        ('NSURLVolumeSupportsPersistentIDsKey', 'string'),
        ('NSURLVolumeSupportsRenamingKey', 'string'),
        ('NSURLVolumeSupportsRootDirectoryDatesKey', 'string'),
        ('NSURLVolumeSupportsSparseFilesKey', 'string'),
        ('NSURLVolumeSupportsSymbolicLinksKey', 'string'),
        ('NSURLVolumeSupportsVolumeSizesKey', 'string'),
        ('NSURLVolumeSupportsZeroRunsKey', 'string'),
        ('NSURLVolumeTotalCapacityKey', 'string'),
        ('NSURLVolumeURLForRemountingKey', 'string'),
        ('NSURLVolumeURLKey', 'string'),
        ('NSURLVolumeUUIDStringKey', 'string'),
    ],
    'CoreGraphics': [
        ('kCGColorSpaceSRGB', 'string'),
    ],
    'CoreImage': [
        ('kCIInputImageKey', 'string'),
        ('kCIOutputImageKey', 'string'),
        ('kCIInputScaleKey', 'string'),
    ],
    'CoreLocation': [
        ('kCLErrorDomain', 'string'),
    ],
    'CoreMedia': [
        ('kCMSampleAttachmentKey_DisplayImmediately', 'string'),
        ('kCMSampleAttachmentKey_DoNotDisplay', 'string'),
    ],
    'CoreTelephony': [
        ('CTRadioAccessTechnologyCDMA1x', 'string'),
        ('CTRadioAccessTechnologyCDMAEVDORev0', 'string'),
        ('CTRadioAccessTechnologyCDMAEVDORevA', 'string'),
        ('CTRadioAccessTechnologyCDMAEVDORevB', 'string'),
        ('CTRadioAccessTechnologyDidChangeNotification', 'string'),
        ('CTRadioAccessTechnologyEdge', 'string'),
        ('CTRadioAccessTechnologyGPRS', 'string'),
        ('CTRadioAccessTechnologyHSDPA', 'string'),
        ('CTRadioAccessTechnologyHSUPA', 'string'),
        ('CTRadioAccessTechnologyLTE', 'string'),
        ('CTRadioAccessTechnologyWCDMA', 'string'),
        ('CTRadioAccessTechnologyeHRPD', 'string'),
    ],
    'CoreText': [
        ('kCTFontPostScriptNameKey', 'string'),
        ('kCTFontSymbolicTrait', 'string'),
        ('kCTFontTraitsAttribute', 'string'),
        ('kCTForegroundColorFromContextAttributeName', 'string'),
        ('kCTRunDelegateAttributeName', 'string'),
        ('kCTSuperscriptAttributeName', 'string'),
    ],
    'CoreVideo': [
        ('kCVPixelBufferCGBitmapContextCompatibilityKey', 'string'),
        ('kCVPixelBufferCGImageCompatibilityKey', 'string'),
    ],
    'EventKit': [
        ('EKEventStoreChangedNotification', 'string'),
    ],
    'Foundation': [
        ('NSErrorFailingURLStringKey', 'string'),
        ('NSKeyedArchiveRootObjectKey', 'string'),
        ('NSMetadataItemURLKey', 'string'),
        ('NSMetadataQueryUpdateAddedItemsKey', 'string'),
        ('NSMetadataQueryUpdateChangedItemsKey', 'string'),
        ('NSMetadataQueryUpdateRemovedItemsKey', 'string'),
        ('NSURLAuthenticationMethodClientCertificate', 'string'),
        ('NSURLErrorFailingURLPeerTrustErrorKey', 'string'),
        ('NSUbiquitousKeyValueStoreChangedKeysKey', 'string'),
        ('NSMetadataItemFSNameKey', 'string'),
        ('NSMetadataQueryUbiquitousDocumentsScope', 'string'),
        ('NSURLAuthenticationMethodHTTPBasic', 'string'),
        ('NSURLAuthenticationMethodHTTPDigest', 'string'),
        ('NSURLSessionDownloadTaskResumeData', 'string'),
        ('NSCharacterConversionException', 'string'),
        ('NSInvalidArchiveOperationException', 'string'),
        ('NSStreamDataWrittenToMemoryStreamKey', 'string'),
        ('NSStreamFileCurrentOffsetKey', 'string'),
        ('NSStreamNetworkServiceType', 'string'),
        ('NSStreamNetworkServiceTypeVoIP', 'string'),
        ('NSTextCheckingCityKey', 'string'),
        ('NSTextCheckingCountryKey', 'string'),
        ('NSTextCheckingStateKey', 'string'),
        ('NSTextCheckingStreetKey', 'string'),
        ('NSTextCheckingZIPKey', 'string'),
        ('NSUndefinedKeyException', 'string'),
        ('NSUndoManagerDidCloseUndoGroupNotification', 'string'),
        ('NSUndoManagerDidRedoChangeNotification', 'string'),
        ('NSUndoManagerDidUndoChangeNotification', 'string'),
        ('NSXMLParserErrorDomain', 'string'),
    ],
    'GLKit': [
        ('GLKTextureLoaderOriginBottomLeft', 'string'),
    ],
    'ImageIO': [
        ('kCGImageDestinationLossyCompressionQuality', 'string'),
        ('kCGImageProperty8BIMDictionary', 'string'),
        ('kCGImagePropertyCIFFDictionary', 'string'),
        ('kCGImagePropertyDNGDictionary', 'string'),
        ('kCGImagePropertyExifAuxDictionary', 'string'),
        ('kCGImagePropertyExifDateTimeDigitized', 'string'),
        ('kCGImagePropertyExifDateTimeOriginal', 'string'),
        ('kCGImagePropertyExifDictionary', 'string'),
        ('kCGImagePropertyGIFDelayTime', 'string'),
        ('kCGImagePropertyGIFDictionary', 'string'),
        ('kCGImagePropertyGIFLoopCount', 'string'),
        ('kCGImagePropertyGIFUnclampedDelayTime', 'string'),
        ('kCGImagePropertyGPSAltitude', 'string'),
        ('kCGImagePropertyGPSDateStamp', 'string'),
        ('kCGImagePropertyGPSDictionary', 'string'),
        ('kCGImagePropertyGPSLatitude', 'string'),
        ('kCGImagePropertyGPSLatitudeRef', 'string'),
        ('kCGImagePropertyGPSLongitude', 'string'),
        ('kCGImagePropertyGPSLongitudeRef', 'string'),
        ('kCGImagePropertyGPSTimeStamp', 'string'),
        ('kCGImagePropertyIPTCDictionary', 'string'),
        ('kCGImagePropertyJFIFDictionary', 'string'),
        ('kCGImagePropertyMakerAppleDictionary', 'string'),
        ('kCGImagePropertyMakerCanonDictionary', 'string'),
        ('kCGImagePropertyMakerNikonDictionary', 'string'),
        ('kCGImagePropertyOrientation', 'string'),
        ('kCGImagePropertyPNGDictionary', 'string'),
        ('kCGImagePropertyPixelHeight', 'string'),
        ('kCGImagePropertyPixelWidth', 'string'),
        ('kCGImagePropertyRawDictionary', 'string'),
        ('kCGImagePropertyTIFFDictionary', 'string'),
        ('kCGImagePropertyTIFFMake', 'string'),
        ('kCGImagePropertyTIFFModel', 'string'),
        ('kCGImageSourceShouldAllowFloat', 'string'),
        ('kCGImageSourceShouldCache', 'string'),
        ('kCGImageSourceTypeIdentifierHint', 'string'),
    ],
    'MapKit': [
        ('MKLaunchOptionsDirectionsModeDriving', 'string'),
        ('MKLaunchOptionsDirectionsModeKey', 'string'),
        ('MKLaunchOptionsDirectionsModeWalking', 'string'),
        ('MKLaunchOptionsMapCenterKey', 'string'),
        ('MKLaunchOptionsMapTypeKey', 'string'),
        ('MKLaunchOptionsShowsTrafficKey', 'string'),
    ],
    'MediaPlayer': [
        ('MPMediaEntityPropertyPersistentID', 'string'),
        ('MPMediaItemPropertyAlbumPersistentID', 'string'),
        ('MPMediaItemPropertyAlbumTrackNumber', 'string'),
        ('MPMediaItemPropertyArtistPersistentID', 'string'),
        ('MPMediaItemPropertyArtwork', 'string'),
        ('MPMediaItemPropertyAssetURL', 'string'),
        ('MPMediaItemPropertyComments', 'string'),
        ('MPMediaItemPropertyIsCloudItem', 'string'),
        ('MPMediaItemPropertyLastPlayedDate', 'string'),
        ('MPMediaItemPropertyLyrics', 'string'),
        ('MPMediaItemPropertyMediaType', 'string'),
        ('MPMediaItemPropertyPersistentID', 'string'),
        ('MPMediaItemPropertyPlayCount', 'string'),
        ('MPMediaItemPropertyPlaybackDuration', 'string'),
        ('MPMediaItemPropertyRating', 'string'),
        ('MPMediaItemPropertyReleaseDate', 'string'),
        ('MPMediaItemPropertySkipCount', 'string'),
        ('MPMediaLibraryDidChangeNotification', 'string'),
        ('MPMediaPlaylistPropertyName', 'string'),
        ('MPMediaPlaylistPropertyPersistentID', 'string'),
        ('MPMediaPlaybackIsPreparedToPlayDidChangeNotification', 'string'),
        ('MPMoviePlayerThumbnailErrorKey', 'string'),
        ('MPMoviePlayerThumbnailImageKey', 'string'),
        ('MPMoviePlayerThumbnailImageRequestDidFinishNotification', 'string'),
        ('MPMusicPlayerControllerPlaybackStateDidChangeNotification', 'string'),
    ],
    'MobileCoreServices': [
        ('kUTTagClassFilenameExtension', 'string'),
        ('kUTTagClassMIMEType', 'string'),
        ('kUTTypeAudio', 'string'),
        ('kUTTypeAudioInterchangeFileFormat', 'string'),
        ('kUTTypeAudiovisualContent', 'string'),
        ('kUTTypeBMP', 'string'),
        ('kUTTypeCompositeContent', 'string'),
        ('kUTTypeConformsToKey', 'string'),
        ('kUTTypeContent', 'string'),
        ('kUTTypeData', 'string'),
        ('kUTTypeFileURL', 'string'),
        ('kUTTypeFlatRTFD', 'string'),
        ('kUTTypeGIF', 'string'),
        ('kUTTypeHTML', 'string'),
        ('kUTTypeItem', 'string'),
        ('kUTTypeJPEG', 'string'),
        ('kUTTypeJPEG2000', 'string'),
        ('kUTTypeMP3', 'string'),
        ('kUTTypeMPEG4', 'string'),
        ('kUTTypeMPEG4Audio', 'string'),
        ('kUTTypePDF', 'string'),
        ('kUTTypePNG', 'string'),
        ('kUTTypePlainText', 'string'),
        ('kUTTypePropertyList', 'string'),
        ('kUTTypeRTF', 'string'),
        ('kUTTypeRTFD', 'string'),
        ('kUTTypeTIFF', 'string'),
        ('kUTTypeTagSpecificationKey', 'string'),
        ('kUTTypeText', 'string'),
        ('kUTTypeURL', 'string'),
        ('kUTTypeUTF8PlainText', 'string'),
        ('kUTTypeVCard', 'string'),
        ('kUTTypeVideo', 'string'),
        ('kUTTypeWaveformAudio', 'string'),
        ('kUTTypeWebArchive', 'string'),
        ('kUTTypeZipArchive', 'string'),
    ],
    'PassKit': [
        ('PKPaymentNetworkAmex', 'string'),
        ('PKPaymentNetworkMasterCard', 'string'),
        ('PKPaymentNetworkVisa', 'string'),
    ],
    'Photos': [
        ('PHImageErrorKey', 'string'),
        ('PHImageResultIsDegradedKey', 'string'),
    ],
    'QuartzCore': [
        ('kCATransactionAnimationDuration', 'string'),
        ('kCAAnimationCubic', 'string'),
        ('kCAAnimationCubicPaced', 'string'),
        ('kCAAnimationPaced', 'string'),
        ('kCAFillRuleEvenOdd', 'string'),
        ('kCALineCapRound', 'string'),
        ('kCALineJoinBevel', 'string'),
        ('kCALineJoinRound', 'string'),
    ],
    'Security': [
        ('kSecAttrAuthenticationType', 'string'),
        ('kSecAttrAuthenticationTypeDefault', 'string'),
        ('kSecAttrCreationDate', 'string'),
        ('kSecAttrIsPermanent', 'string'),
        ('kSecAttrKeySizeInBits', 'string'),
        ('kSecAttrSecurityDomain', 'string'),
        ('kSecAttrServer', 'string'),
        ('kSecAttrSynchronizableAny', 'string'),
        ('kSecClassIdentity', 'string'),
        ('kSecClassInternetPassword', 'string'),
        ('kSecImportExportPassphrase', 'string'),
        ('kSecImportItemIdentity', 'string'),
        ('kSecMatchLimitAll', 'string'),
        ('kSecMatchPolicy', 'string'),
        ('kSecPrivateKeyAttrs', 'string'),
        ('kSecPublicKeyAttrs', 'string'),
        ('kSecAttrKeyClassPrivate', 'string'),
    ],
    'Social': [
        ('SLServiceTypeSinaWeibo', 'string'),
        ('SLServiceTypeTencentWeibo', 'string'),
    ],
    'StoreKit': [
        ('SKStoreProductParameterAffiliateToken', 'string'),
        ('SKStoreProductParameterCampaignToken', 'string'),
        ('SKStoreProductParameterProviderToken', 'string'),
    ],
    'SystemConfiguration': [
        ('kSCEntNetVPN', 'string'),
        ('kSCPropNetVPNAuthName', 'string'),
        ('kSCPropNetVPNAuthPassword', 'string'),
        ('kVPNConfigurationKeyCertificateRef', 'string'),
        ('kVPNConfigurationKeyPersistentRef', 'string'),
    ],
    'UIKit': [
        ('NSAttachmentAttributeName', 'string'),
        ('NSBackgroundColorAttributeName', 'string'),
        ('NSFontAttributeName', 'string'),
        ('NSForegroundColorAttributeName', 'string'),
        ('NSShadowAttributeName', 'string'),
        ('UIAccessibilityVoiceOverStatusChanged', 'string'),
        ('UIApplicationOpenSettingsURLString', 'string'),
        ('UIApplicationStatusBarFrameUserInfoKey', 'string'),
        ('UICollectionElementKindSectionFooter', 'string'),
        ('UICollectionElementKindSectionHeader', 'string'),
        ('UIPasteboardTypeListURL', 'string'),
        ('UITableViewIndexSearch', 'string'),
        ('UIKeyInputDownArrow', 'string'),
        ('UIKeyInputEscape', 'string'),
        ('UIKeyInputLeftArrow', 'string'),
        ('UIKeyInputRightArrow', 'string'),
        ('UIKeyInputUpArrow', 'string'),
        ('NSCharacterEncodingDocumentAttribute', 'string'),
        ('NSDocumentTypeDocumentAttribute', 'string'),
        ('NSHTMLTextDocumentType', 'string'),
        ('NSKernAttributeName', 'string'),
        ('NSLinkAttributeName', 'string'),
        ('NSParagraphStyleAttributeName', 'string'),
        ('NSPlainTextDocumentType', 'string'),
        ('NSRTFDTextDocumentType', 'string'),
        ('NSRTFTextDocumentType', 'string'),
        ('NSStrikethroughStyleAttributeName', 'string'),
        ('NSStrokeColorAttributeName', 'string'),
        ('NSStrokeWidthAttributeName', 'string'),
        ('NSTextEffectAttributeName', 'string'),
        ('NSTextEffectLetterpressStyle', 'string'),
        ('NSUnderlineColorAttributeName', 'string'),
        ('NSUnderlineStyleAttributeName', 'string'),
        ('UIAccessibilityAnnouncementDidFinishNotification', 'string'),
        ('UIAccessibilitySpeechAttributeLanguage', 'string'),
        ('UIAccessibilitySpeechAttributePitch', 'string'),
        ('UIActivityTypeAddToReadingList', 'string'),
        ('UIActivityTypeAirDrop', 'string'),
        ('UIActivityTypeAssignToContact', 'string'),
        ('UIActivityTypeCopyToPasteboard', 'string'),
        ('UIActivityTypeMail', 'string'),
        ('UIActivityTypeMessage', 'string'),
        ('UIActivityTypePostToFacebook', 'string'),
        ('UIActivityTypePostToFlickr', 'string'),
        ('UIActivityTypePostToTencentWeibo', 'string'),
        ('UIActivityTypePostToTwitter', 'string'),
        ('UIActivityTypePostToVimeo', 'string'),
        ('UIActivityTypePostToWeibo', 'string'),
        ('UIActivityTypePrint', 'string'),
        ('UIActivityTypeSaveToCameraRoll', 'string'),
        ('UIApplicationLaunchOptionsLocationKey', 'string'),
        ('UIApplicationLaunchOptionsURLKey', 'string'),
        ('UIApplicationWillChangeStatusBarFrameNotification', 'string'),
        ('UIContentSizeCategoryDidChangeNotification', 'string'),
        ('UIDeviceProximityStateDidChangeNotification', 'string'),
        ('UIDocumentStateChangedNotification', 'string'),
        ('UIFontDescriptorNameAttribute', 'string'),
        ('UIFontTextStyleBody', 'string'),
        ('UIFontTextStyleFootnote', 'string'),
        ('UIFontTextStyleHeadline', 'string'),
        ('UIFontTextStyleSubheadline', 'string'),
        ('UIImagePickerControllerReferenceURL', 'string'),
        ('UIKeyboardWillChangeFrameNotification', 'string'),
        ('UIMenuControllerWillHideMenuNotification', 'string'),
        ('UIPageViewControllerOptionSpineLocationKey', 'string'),
        ('UITableViewSelectionDidChangeNotification', 'string'),
        ('UITextFieldTextDidBeginEditingNotification', 'string'),
        ('UITextFieldTextDidEndEditingNotification', 'string'),
        ('UITextViewTextDidBeginEditingNotification', 'string'),
        ('UITextViewTextDidEndEditingNotification', 'string'),
        ('UITransitionContextFromViewControllerKey', 'string'),
        ('UITransitionContextToViewControllerKey', 'string'),
        ('UIWindowDidBecomeHiddenNotification', 'string'),
        ('UIWindowDidResignKeyNotification', 'string'),
    ],
}

flat = [(framework, symbol) for framework, entries in constants.items()
        for symbol, _ in entries]
if len(flat) != 505 or len(set(flat)) != len(flat):
    raise SystemExit("corpus object-constant manifest must contain 505 unique exports")

source_header = r'''#import <Foundation/Foundation.h>
#import <Foundation/Foundation+LC32.h>

/* Generated from the exhaustive 40-app ARM32 binding contract. String
 * constants bind to the exact native object, preserving host dictionary-key
 * and notification identity. The literal remains a valid fallback only when
 * a removed host symbol no longer exists. */
static id LC32CorpusStringConstant(const char *symbol, NSString *fallback) {
    const uint64_t hostObject = LC32Dlsym(symbol, NO);
    if(hostObject) [fallback bindHostSelf:hostObject];
    return fallback;
}

'''

for framework, entries in constants.items():
    directory = root / framework
    directory.mkdir(parents=True, exist_ok=True)
    output = directory / "LC32CorpusObjectConstants.m"
    existing_sources = [candidate for candidate in directory.rglob("*.m")
                        if candidate != output]
    generated_directory = root / ".generated" / framework
    if generated_directory.is_dir():
        existing_sources.extend(generated_directory.rglob("*.m"))
    existing_text = "\n".join(candidate.read_text() for candidate in existing_sources)
    original_count = len(entries)
    entries = [(symbol, kind) for symbol, kind in entries
               if symbol not in existing_text]
    declarations = []
    initializers = []
    for index, (symbol, kind) in enumerate(entries):
        storage = f"LC32CorpusObjectConstant{index}"
        declarations.append(f'id {storage} __asm__("_{symbol}");')
        if kind == "string":
            initializers.append(
                f'    {storage} = LC32CorpusStringConstant("{symbol}", @"{symbol}");')
        elif kind.startswith("merge:"):
            merge_type = kind.split(":", 1)[1]
            initializers.append(
                f'    {storage} = [[NSMergePolicy alloc] initWithMergeType:{merge_type}];\n'
                f'    const uint64_t {storage}Host = LC32Dlsym("{symbol}", NO);\n'
                f'    if({storage}Host) [{storage} bindHostSelf:{storage}Host];')
        else:
            raise SystemExit(f"unsupported constant kind {kind!r} for {framework}:{symbol}")
    source = source_header
    if framework == "CoreData":
        source += "#import <CoreData/CoreData.h>\n\n"
    source += "\n".join(declarations) + "\n\n"
    source += "__attribute__((constructor))\n"
    source += f"static void LC32Initialize{framework}CorpusConstants(void) {{\n"
    source += "\n".join(initializers) + "\n}\n"
    if entries:
        output.write_text(source)
    elif output.exists():
        output.unlink()
    print(f"{framework}: {len(entries)} added, {original_count - len(entries)} supplied by nightly")
glkit = root / "GLKit/LC32MatrixConstants.m"
glkit_sources = [candidate for candidate in root.rglob("*.m")
                 if candidate != glkit and "GLKMatrix4Identity" in candidate.read_text()]
if glkit_sources:
    print("GLKit: nightly already exports GLKMatrix4Identity")
else:
    glkit.write_text("#import <GLKit/GLKit.h>\nconst GLKMatrix4 GLKMatrix4Identity = {{1,0,0,0, 0,1,0,0, 0,0,1,0, 0,0,0,1}};\n")
