display_name: døPe
icon: snap/gui/dope.png

keywords:
  - Music
  - Audio
  - retro music player
  - Local
  - Songs
  - Offline

generic_name: Local Music Player
categories:
  - Music

startup_notify: true